import re

from django.core.exceptions import ValidationError


# def int_list(value):
# 	try:
# 		pass
# 	except:
# 		raise ValidationError('message')
